
targets:
  $default:
    sources:
      - lib/**
      - web/**

    builders:
      sqlite3mc_web_worker_generator:
        enabled: true
builders:
  sqlite3mc_web_worker_generator:
    import: "package:sqlite3mc_drift_dev/sqlite3mc_drift_dev.dart"
    builder_factories: [ "sqlite3mcWebWorkersGenerator" ]
    build_extensions: { r'lib/database/connection/web.dart': [ "*.ok","web/file.worker.js" ] }
    auto_apply: root_package
    build_to: source