name: sqlite3mc_drift_dev
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  build: ^2.3.1

  process_run: ^0.12.3+2
  build_web_compilers: ^3.2.6
  webdev: ^2.7.11
  source_gen: ^1.2.6

dev_dependencies:
  build_runner: ^2.3.0
  lints:

dependency_overrides:
