set(triple wasm32-wasi)
set(wasi_sysroot $ENV{WASI_SDK_PATH}/share/wasi-sysroot/)
set(INCLUDE_DIRS $ENV{WASI_SDK_PATH}/share/wasi-sysroot/include)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_C_COMPILE_OPTIONS_SYSROOT "--sysroot=${wasi_sysroot}")
set(CMAKE_SYSROOT ${wasi_sysroot})
set(CMAKE_LINKER $ENV{WASI_SDK_PATH}/bin/wasm-ld)

set(CMAKE_C_COMPILER $ENV{WASI_SDK_PATH}/bin/clang)
set(CMAKE_C_COMPILER_WORKS 1)
