name: sqlite3mc_flutter_libs
description: Flutter plugin to include native SQLite3 Multiple Ciphers libraries in your app
version: 0.0.1
homepage: https://github.com/simolus3/sqlite3.dart/tree/master/slcipher_flutter_libs
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.1"

dependencies:
  flutter:
    sdk: flutter
  lints:
flutter:
  plugin:
    # We use the same class names as sqlite3_flutter_libs since users should never depend on both packages at the same
    # time, not even transitively.
    platforms:
      android:
        package: eu.simonbinder.sqlite3_flutter_libs
        pluginClass: Sqlite3FlutterLibsPlugin
      ios:
        pluginClass: Sqlite3FlutterLibsPlugin
      macos:
        pluginClass: Sqlite3FlutterLibsPlugin
      linux:
        pluginClass: Sqlite3FlutterLibsPlugin
      windows:
        pluginClass: Sqlite3FlutterLibsPlugin

