# This configures how `build_runner` and associated builders should behave.
# For more information, see https://pub.dev/packages/build_config
# This configures how `build_runner` and associated builders should behave.
# For more information, see https://pub.dev/packages/build_config
global_options:



targets:
  $default:

    # Reducing sources makes the build slightly faster (some of these are required
    # to exist in the default target).
    sources:
      - lib/**
      - web/**
      - "tool/**"
      - pubspec.yaml
      - lib/$lib$
      - $package$
      - "package:sqlite3mc_drift_database/assets/**"
    builders:
      drift_dev:
        # These options change how drift generates code
        options:
          # Drift analyzes SQL queries at compile-time. For this purpose, it needs to know which sqlite3
          # features will be available. We depend on `sqlite3_flutter_libs`, which lets us use the latest
          # version with fts5 enabled.
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules: [fts5]

          # This allows us to share a drift database across isolates (or different tabs on the web)
          generate_connect_constructor: true
          # These options are generally recommended: https://drift.simonbinder.eu/docs/advanced-features/builder_options/#recommended-options
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          scoped_dart_components: true





      sqlite3mc_drift_dev:sqlite3mc_web_worker_generator:
        enabled: true
        options:
          input_files: ['lib/database/connection/web.dart']
          output_files: ['web/sqlite3mc.wasm', 'web/sqlite3mc.debug.wasm','web/file.worker.js','web/worker.dart.js',"lib/database/connection/worker.dart",'web/post_message_sab_shim.js']
          root: ''

# build_web_compilers writes a hidden asset, but we want an asset in `web/` for
# flutter to see. So, copy that output. Again, this is not needed for most apps.
builders:



