name: app
description: A cross-platform todo tracker built with drift.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.3.0
  flutter_colorpicker: ^1.0.3
  flutter_riverpod: ^1.0.3
  go_router: ^3.0.6
  intl: ^0.17.0
  http: ^0.13.4 # used to load sqlite3 wasm files on the web
  sqlite3mc_flutter_libs: ^0.5.5
  sqlite3mc_drift_database:
  sqlite3: ^1.7.0
  path_provider: ^2.0.9
  path: ^1.8.0
  riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  # We use this to compile the shared web worker for the web database. This dependency
  # isn't required for most apps. You only need it if you want to target the web, use
  # web workers for drift AND want to compile those web workers through `build_runner`.
  # Either way, using this package with Flutter requires a delicate setup described in
  # `build.yaml`.
  build: ^2.2.1
  drift_dev: ^2.3.0
  sqlite3mc_drift_dev:


flutter:
  uses-material-design: true

# We override dependencies to ensure that we always use the packages from
# this repository. In your app, just depend on the latest drift version.
dependency_overrides:
  sqlite3mc_flutter_libs:
    path: ../../packages/sqlite3mc_flutter_libs
  sqlite3mc_drift_database:
    path: ../../packages/sqlite3mc_drift_database
  sqlite3mc_drift_dev:
    path: ../../packages/sqlite3mc_drift_dev


