name: sqlite3mc_drift_database
description: A package providing SQLite Multiple Ciphers to drift.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  sqlite3: ^1.9.1
  collection: ^1.15.0
  ffi: '>=1.2.1 <3.0.0'
  js: ^0.6.4
  meta: ^1.3.0
  path: ^1.8.0
  convert: ^3.0.2
  sprintf: ^6.0.0
  drift: ^2.3.0
  http: ^0.13.5
  js_bindings: 0.0.6
  logger: ^1.1.0

dev_dependencies:
  build: ^2.2.1
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
  webdev: ^2.7.10
  test: ^1.16.0

