name: Gh-Pages

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master' # or: 'beta', 'dev' or 'master'
      - uses: ./.github/actions/build-examples
        with:
          workingDir: examples/todo_app
          baseHref: /sqlite3mc.dart/app/

